[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ransac"
version = "0.0.1"
dependencies = [
    "numpy",
    'importlib-metadata; python_version>"3.6"',
]